prefect:
  # Prefect server settings
  server:
    host: "localhost"
    port: 4200

  # Flow settings
  flows:
    market_data_collection:
      name: "Market Data Collection"
      description: "Collects market data from Alpaca and Yahoo Finance"
      schedule: "0 * * * *"  # Every hour
      retries: 3
      retry_delay: 60  # seconds

  # Task settings
  tasks:
    collect_market_data:
      retries: 3
      retry_delay: 60
      timeout: 300  # 5 minutes
    store_market_data:
      retries: 3
      retry_delay: 30
      timeout: 180  # 3 minutes 